#!/bin/bash

action=$1
shift

function usage {
  echo "  Customized repeat:"
  echo "    repeat ITEM "
  echo "      mark an item complete then re-enter it"
  echo ""
  exit
}

[ "$action" = "usage" ] && usage

# make sure we have an item number
ITEM=$1
if ! [[ "$ITEM" =~ ^[0-9]+$ ]]; then
    echo "Error! Usage:"
	usage
	exit
fi

# pull the line from the todo file
LINE=$(sed "$ITEM!d" "$TODO_FILE")

if [[ "$LINE" =~ ^\([A-Z]\) ]]; then
	LINE=$(echo "$LINE" | cut -f2- -d ' ') # cut off the priority
fi
if [[ "$LINE" =~ ^[0-9][0-9][0-9][0-9] ]]; then
	LINE=$(echo "$LINE" | cut -f2- -d ' ') # cut off the date
fi

if [[ "$LINE" != "" ]] ; then
    $DO && "$TODO_SH" command do "$ITEM"
    $DO && "$TODO_SH" command add "$LINE"
fi
